const API_URL = `https://api.backendless.com/2E213529-5906-D5D0-FF28-89FD94058C00/FE20BF36-EE6F-4189-878F-2074CFAE2502`;
export const NEWSLETTER_URL = `${API_URL}/data/newsletter`;
export const LOGIN_URL = `${API_URL}/users/login`;
export const LOGOUT_URL = `${API_URL}/users/logout`;
export const GET_USER = `${API_URL}/data/Users`;
export const REGISTER_URL = `${API_URL}/users/register`;
export const NEWS = `${API_URL}/data/news`;
export const TRAVEL = `${API_URL}/data/travel`;
export const FOOTBALL = `${API_URL}/data/footballResult`;
